blank_issues_enabled: false
contact_links:
- name: Reporte de seguridad / vulnerabilidad
  url: https://noticiencias.com/security
  about: Usa este canal para reportar hallazgos sensibles (no crees un issue público).